### PR TITLE
Adding a wrapper for fahrplan-plus v1 api

### PR DESCRIPTION
**Pull request by GamingCoookie**
and bumping copyright to 2022 :)

I think this wrapper could be extended quite a bit

### CODE REVIEW

**Comment by CatoLynx** [comment]
Just letting you know I read the PR and I appreciate it but it'll take a few days until I have time to implement it :)

**Comment by CatoLynx** [comment]
Okay that was a long few days. My issue with your commit is the copyright dates, you just changed them to the current year. The proper way to do it is to extend the range, so you should write 2020-2022. Can you fix that? Then I can merge.

**Comment by GamingCoookie** [comment]
Oh, that's good to hear. I can do that later today when I am home :)

**Comment by CatoLynx** [comment]
I didn't test it but since this is not some huge opensource project... it'll be fine :D

**Pull request merged**
